# Generated by Django 4.0.1 on 2022-02-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookDashboard', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_pics/default.jpg', upload_to='book_pics'),
        ),
    ]
